"""Non-sensitive configuration names shared by both application entry points."""

MAIAGENT_ENV_NAMES = ("MAIAGENT_API_KEY", "MAIAGENT_CHATBOT_ID", "MAIAGENT_API_BASE")
EMAIL_ENV_NAMES = ("GMAIL_USER", "GMAIL_APP_PASS", "RECIPIENTS", "DEFAULT_RECIPIENTS")
RUNTIME_ENV_NAMES = (
    "NEWS_LOOKBACK_DAYS", "MAIAGENT_TIMEOUT_SECONDS", "MAIAGENT_MAX_RSS_CHARS",
    "MAIAGENT_MAX_DDG_CHARS", "DDGS_MAX_WORKERS", "DDGS_MAX_QUERIES", "ENABLE_DDGS",
)
REPORT_TYPES = ("技術新知", "重大事故", "營運政策", "營運爭議", "規範更新")
